### ISSUE TITLE
Add conditional execution

### ISSUE THREAD

**Issue by porglezomp** [a2aaron/fillmore#10]
Should have prefix syntax `cond` and `?`.
The instruction should only execute if the top element on the stack is non-zero.
Conditional execution pops the top value off the stack, and the conditional check pop happens before the instruction gets a chance to pop its values.

For example: with the stack `3 2 1`, the code `? +` will pop `1`, use that to decide that it should add, pop `2` and `3`, and then push `5`.
### Questions:
- Should we pop the top value off the stack? If we don't, things like jumping into code that doesn't expect the condition value becomes more complicated, and probably requires a trampoline location. **Conclusion:** Yes we should.
- Do we need to specifically support a quiet mode if we do? People can do `dup; ? jump 2` if they want it. **Conclusion:** We should support a quiet mode.
- If we support a quiet mode, what should the syntax for it be? Writing `♯ ? ×` vs `? ♯ ×` is confusing, and seems like obviously a bad choice. **Conclusion:** `??` or `¿` are the quiet case.

**Comment by a2aaron** [comment]
I'm assuming that the line "The instruction should only execute if the top element on the stack" means if the top element is non-zero.

To answer the questions:
1. By default, don't pop the top value.
2. If there is popping of the top value, I recommend calling it a `loud` mode (with `b` and `♭` as sigils). It would be `loud cond op`
3. Syntax should be `cond quiet op`, not `quiet cond op`. If we have a loud mode, then `loud cond quiet op` would pop off the top value and (maybe) execute the next instruction quietly.

**Comment by porglezomp** [comment]
Thanks, fixed the typo.
My concern: I think that popping the condition is going to be a _much_ more common use case. You usually want to jump into the middle of some other code, and that code won't be able to pop the condition unless the only way you get there is by conditionally jumping, which necessitates "trampolines," which means you conditionally jump somewhere, pop the condition, and then jump to the place you actually care about.

My counter-proposal:
1. Pop the top value by default.
2. Add a separate operator besides `cond` that handles the quiet case, perhaps `qcond`, with alternate syntax `??` and `¿`. This avoids any potential confusion between `? # op` and `# ? op` by making them `? # op` and `?? op` respectively.
3. We should explicitly allow both `?? # op` and `# ?? op`, they should have identical behavior.

**Comment by porglezomp** [comment]
What do you think about my proposal?

**Comment by a2aaron** [comment]
Quick question, how do operations that also pop values from the stack work?

For example, would `cond add` pop three values, with the top value being the value checked against the `cond` and the next two being added?

I'm assuming yes (plus, this allows for `cond nop` to be optimized as `pop` and other similar things)

**Comment by porglezomp** [comment]
Yes, I would expect the condition to pop first, I'll add that to our spec here.

**Comment by a2aaron** [comment]
For `qcond`, does the operation use the values below the first element? (Aka: would the operation pretend that the top value doesn't exist)

For example, does `?? *` on the stack `[20, 10, 4]` result in `[200, 1]` or `[20, 40]`?

If so, then how would `qcond quiet op` work? Does it push below the top element or directly onto the stack?

For now, I'm gonna assume that qcond will "fake pop" the top value, do the operation, and finally push the original value back onto the stack.

Thus, `[a, b, c]` becomes `[ab, c]` (or `[a, b, ab, c]` if the quiet prefix is present).

**Comment by porglezomp** [comment]
That's a good question, and I don't know, we'll stick with your interpretation for now, if it becomes a problem we can change it.
