### ISSUE TITLE
Add absolute jumps

### ISSUE THREAD

**Issue by porglezomp** [a2aaron/fillmore#11]
The syntax should probably be `to` and `↓`.
Absolute jumps should move directly to the instruction number.
### Alternatives:

Instead of having absolute jumps, labels (see #12) could be restricted to being in jump instructions, and only represent a relative number.

**Comment by a2aaron** [comment]
I'm gonna assume these behaviors:
- If `to` has no arguments, pop off the top element.
  - If there is a `quiet` prefix, don't pop the top element but still read from it.
- If the argument is negative or a float, raise `ValueError`
- If the jump would go before or after the program (ex: `to -1`), raise `IndexError`.
- `to 1` goes to the start of the program. `to 0` is an error.

**Comment by porglezomp** [comment]
I don't like this one much anymore, I think the relative jump labels is better. Make an argument for it if you want to work on it.

**Comment by a2aaron** [comment]
Ok. Closing as not implementing.

**Comment by a2aaron** [comment]
Actually, I lied. I find this very useful for jump labels (#12). `jump @label` seems more of a "go to this exact instruction" instead of a "jump forward n instructions". Thus, it should be parsed/converted as such.

`@label; [...]; jump @label` ->  `@label; [...]; to 3`

seems better than

`@label; [...]; jump @label` ->  `@label; [...]; jump -20`

**Comment by porglezomp** [comment]
Just a note that in actual assembly, something like

```
label:
add #2, r1, r1
b label
```

will probably produce something like

```
add #2, r1, r1
sub pc, #8, pc
```

so actual computers do what you object to. That's not actually a reason to avoid absolute jumps, I just thought it was worth mentioning. If you like them, we'll keep them.

One thing I will insist on: absolute branching should be 0-indexed, instead of 1-indexed as you proposed above.
