### ISSUE TITLE
Add jump labels

### ISSUE THREAD

**Issue by porglezomp** [a2aaron/fillmore#12]
Jump labels should probably have the syntax `@name`, or more properly an `@` followed by any sequence of non-whitespace unicode characters.

`jump @name` should be equivalent to a jump that targets the same location that the label is.
Labels shouldn't occupy an instruction slot, so should either be stored as a lookup table separate from the program, or should be removed by pre-processing the code.

**Comment by a2aaron** [comment]
Are multiple labels allow to share the same place?

For example, is

```
@begining
@stack_set_up
push 4
push 0
push 1
@next_fib
dup
swap 2
add
...
```

valid?

Also, what should happen if there are two labels of the same name? I'm thinking raise a `ValueError`.

**Comment by porglezomp** [comment]
Multiple labels can definitely share the same place. `ValueError` might be the right exception? Look at the list of Python exceptions, and if you don't like any of the, you can always define a custom one.

**Comment by porglezomp** [comment]
I don't see any better error, `ValueError` is potentially appropriate. Give it a good message when you raise it.

**Comment by a2aaron** [comment]
Should jump labels be converted into relative jumps, absolute jumps, or be left as is?

If we do convert them, I think that it should be done so before program evaluation.

**Comment by porglezomp** [comment]
I think we should stick to relative jumps only.
I agree with your evaluation strategy: parsing → lowering/simplification → evaluation.

**Comment by a2aaron** [comment]
Hmm..

Can labels be on the same line as an instruction?

`@label_1 @label_2 quiet add;` should presumably be the same as `quiet add @label_1 @label_2;`

**Comment by porglezomp** [comment]
I think it's a good idea to disallow them on the same "line" as instructions, if people really want to write

```
@label-1 quiet add
```

they can just do

```
@label-1; quiet add
```

If we were to allow them, I would expect `@label1 +` to be different from `+ @label1`, which is one of the main reasons I think it's a bad idea. It's really just not worth the complexity.
