### ISSUE TITLE
Actually parse prefixes

### ISSUE THREAD

**Issue by a2aaron** [a2aaron/fillmore#14]
Currently, the only prefix being parsed is `quiet` and it is parsed within the `parse_program()` function. Either have `parse_program()` parse instructions entirely and yeild `Instr` objects or have `Instr` parse prefixes entirely.

(The first option will require us to move `sigil_to_opcode` into `parse_program()')

**Comment by porglezomp** [comment]
Another option is to have some syntax that properly distinguishes the prefix from the instruction, perhaps something like `quiet: add` or `quiet | add`. I'm not sure if I like this very much, but it deserves consideration.

**Comment by porglezomp** [comment]
I think I like the first option the most though.

**Comment by porglezomp** [comment]
Are you going to do this after we merge my work, since I already moved some parsing out?

**Comment by a2aaron** [comment]
Yes, we'll merge your PR first and mine second.

**Comment by porglezomp** [comment]
Do you have any more comments on my PR that I should work on tonight?

**Comment by porglezomp** [comment]
Was this included in the PR I just merged?

**Comment by a2aaron** [comment]
Yes, it was part of #25, in [this commit](https://github.com/a2aaron/fillmore/pull/25/commits/cc49a2ab4356d0829f3ba9642e7ddc8fbcdeded7).

Note that I did not parse prefixes in Instr as I thought that `parse_program` should handle that job.
