### ISSUE TITLE
Set up fancier testing environment

### ISSUE THREAD

**Issue by porglezomp** [a2aaron/fillmore#18]
We should use something like [tox](https://tox.readthedocs.org/en/latest/) for testing so that we can easily run multiple platforms locally as well as have special testing dependencies. (I'd like to be able to require [pytest-timeout](https://pypi.python.org/pypi/pytest-timeout), for instance.)

**Comment by a2aaron** [comment]
This will be added in the next PR (which will be for jump labels)
